### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nick42d** [nick42d/youtui#3]
- [ ] Implement sorting
- [ ] Attempt to reduce memory usage by disabling logs
- [ ] Simplify "StateUpdater" architecture.
- [ ] Redirect callback messages to top level (And consider using callback messages instead).
